### ISSUE TITLE
iOS - Re-prompt User for Location Permission?

### ISSUE THREAD

**Issue by lin-brian-l** [NativeScript/nativescript-geolocation#113]
My app requires the user's location upon logging in so that it can be used to recommend places near them. However, if a user denies permission to the app on iOS, any subsequent attempts to retrieve the user's location with `getCurrentLocation()` will throw the error `Authorization Denied.`. Is there a way to re-authorize the app to access the user's location?

**Comment by DimitarTachev** [comment]
Hi @lin-brian-l,

That's a limitation in the OS. The iOS will only prompt the user once. In order to enable permissions after denying them, the users have to go through the Settings app.

I will leave this issue open as we could try improving the plugin by redirecting the users to the Settings app when the permissions are denied.

**Comment by lin-brian-l** [comment]
Thank you for the fast response @DimitarTachev, I appreciate the help. It's a shame that iOS does this, but now I can point users in the right direction. Thanks again!

**Comment by ann1111** [comment]
HI @DimitarTachev ,

         Me too facing the same issue have we got the solution to get location in IOS like Android ?
