### ISSUE TITLE
Remove "requireModules": ["nativescript-geolocation"] from src/package.json

### ISSUE THREAD

**Issue by jeremypele** [NativeScript/nativescript-geolocation#234]
There is a snapshot generation issue with the latest nativescript update.

I've replicated with a fork => https://github.com/jeremypele/nativescript-geolocation
Run `npm run run-snapshot` in the angular demo folder

snapshot generation fails because of the src/package.json and the presence of
```
"android": {
        "v8Flags": "--expose_gc",
        "requireModules": ["nativescript-geolocation"]
    }
```
Closing and letting this as a trace for anyone facing the same issue.

Issue was coming from nativescript-permission where neither `android` nor `androidx`  accessor was available.

Should be removed from demos folders IMO, other people may face that very same issue

Ref: https://github.com/NativeScript/nativescript-dev-webpack/issues/1018

**Comment by tgpetrov** [comment]
Hi @jeremypele 
Thank you for posting this. Indeed someone running the demo with snapshot will hit this issue, which you correctly observed comes from the nativescript-permissions plugin. Indeed removing the `requireModules` from the demo, will make the app runnable even with the snapshot option. However, this is only because the plugin (and its dependency nativescript-permissions) will not be included in the snapshot. As we want to check whether the plugin in snapshotable we prefer to keep this code in the demo app. Until the issue in nativescript-premissions is resolved, the demo should be run without the snapshot flag.
