### ISSUE TITLE
Mock locations not received

### ISSUE THREAD

**Issue by surdu** [NativeScript/nativescript-geolocation#64]
I have [Lockito](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito&hl=en) setup to send mock locations on my OnePlus 3T. I see that Google Maps shows the fake locations, so I know that Lockito works correctly, but in my application, the location change handler never triggers.

PS: I took care so that the mock accuracy in bellow desider accuracy.

**Comment by surdu** [comment]
I have a small update: even with mock locations enabled, I still get the real location ... This is very peculiar...

**Comment by DimitarTachev** [comment]
Hi @surdu 

The problem was that the plugin was based on the native Android location manager, not the Google Play Services one.

We had a lot of issues because of this approach and we fully replaced it with the Google Play Services one (used by Google Maps). The watchLocation method could use mock locations now (however the getCurrentLocation method is still working only with real locations).

I hope this is applicable to you.

You could check the v4.0.0 release notes [here](https://github.com/NativeScript/nativescript-geolocation/releases/tag/v4.0.0).
