### ISSUE TITLE
Location-monitor.d.ts Typescript file has wrong number of parameters for watchLocation

### ISSUE THREAD

**Issue by Brainvise** [NativeScript/nativescript-geolocation#7]
https://github.com/NativeScript/nativescript-geolocation/blob/master/source/location-monitor.d.ts#L34 This method should have 3 parameters: successCallback, errorCallback and options, not just options. Trying to pass the correct parameters causes Typescript to error out before compilation.

**Comment by aderbas** [comment]
+1
Same issue.
```typescript
var options = {
  desiredAccuracy: 3,
  updateDistance: 10,
  maximumAge: 20000,
  timeout: 20000
};
// watch geolocation
export function enableWatch(args){
  geolocation.watchLocation(
    (loc) => {
      console.log(loc);
    }, (e) => {
      console.log(e);
    },
    options
  );
}
```
Error: Supplied parameters do not match any signature of call target

**Comment by db386** [comment]
Same issue. Plugin as-is not usable with typescript. Fixed by updating signature in https://github.com/NativeScript/nativescript-geolocation/blob/master/source/location-monitor.d.ts#L34.

Original:
`export function watchLocation(options): Number;`

Fix:
`export function watchLocation(successCallback: (location: Location) => void, errorCallback: (err: Error) => void, options): Number;`

**Comment by hshristov** [comment]
Thanks for reporting this. It is fixed in the master branch. 
Will update npm soon.
