### ISSUE TITLE
iOS demo app improvements

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nativescript-geolocation#73]
Using the app on iOS simulator I noticed the following:

- If I try to get the current location it doesn't prompt to enable Location service.
- After pressing 'Start monitoring' button it only shows a few location points and stops.

On a real device, the same as above issues happen plus app does not prompt to enable wi-fi which seems vital.

**Comment by lini** [comment]
First issue should be fixed with #102 
I think the second issue is normal behavior for iOS - when you don't move the phone you stop getting location updates - the last location shown is the current one. If you move the phone (or select something else from the Debug > Location menu on the iOS Simulator) you should get new values.

Also tested on a real device with iOS 11.2 and the app did ask to turn Wi-Fi on when requesting a location permission.
